// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ember-redesign-field-journal/FieldJournal.tsx": () => import("../components/mockups/ember-redesign-field-journal/FieldJournal.tsx"),
  "./components/mockups/ember-redesign-sanctuary/Sanctuary.tsx": () => import("../components/mockups/ember-redesign-sanctuary/Sanctuary.tsx"),
  "./components/mockups/ember-redesign-den/Den.tsx": () => import("../components/mockups/ember-redesign-den/Den.tsx")
};
